default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: valleyhackathon_development

test:
  <<: *default
  database: valleyhackathon_test

production:
  <<: *default
  database: valleyhackathon_production
